// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetAllContainers():Promise<Array<model.Container>>;

export function GetAllTypes():Promise<Array<model.PublicType>>;
