// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {compose} from '../models';
import {model} from '../models';

export function CreateContainer(arg1:compose.CreateContainerRequest):Promise<void>;

export function GenerateDockerCompose():Promise<void>;

export function GetAllContainers():Promise<Array<model.Container>>;

export function GetAllTypes():Promise<Array<model.PublicType>>;
