// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateContainer(arg1) {
  return window['go']['backend']['App']['CreateContainer'](arg1);
}

export function CreateDataType(arg1) {
  return window['go']['backend']['App']['CreateDataType'](arg1);
}

export function DeleteContainer(arg1) {
  return window['go']['backend']['App']['DeleteContainer'](arg1);
}

export function GenerateDockerCompose() {
  return window['go']['backend']['App']['GenerateDockerCompose']();
}

export function GetAllContainers() {
  return window['go']['backend']['App']['GetAllContainers']();
}

export function GetAllTypes() {
  return window['go']['backend']['App']['GetAllTypes']();
}
